In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

In [24]:
np.zeros((2,3))
np.ones((3,4)) #3x4 array of 1's'
np.empty((1,8)) # floats
np.arange(1,10,2) #array from 1 to 10, increment by 2

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

array([1, 3, 5, 7, 9])

In [31]:
np.array([[1, 1], [2, 2], [3, 3]])  #2d array
np.arange(24).reshape(4,3,2) #3d array: 4 x 3 x 2


array([[1, 1],
       [2, 2],
       [3, 3]])

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [52]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a
np.insert(a,4,5)  #if not specifying axis, flattens array and adds value 5 as 4th element
np.insert(a,2,5,axis=0) # adds 5 as row2
np.insert(a,2,5,axis=1) # adds 5 as col2

array([[1, 1],
       [2, 2],
       [3, 3]])

array([1, 1, 2, 2, 5, 3, 3])

array([[1, 1],
       [2, 2],
       [5, 5],
       [3, 3]])

array([[1, 1, 5],
       [2, 2, 5],
       [3, 3, 5]])

In [53]:
a += 1  #adds 1 to each element, inplace=True
a

array([[2, 2],
       [3, 3],
       [4, 4]])

In [58]:
np.linspace(1,24,4)  #4 element array of equal distances from 1 to 24

array([  1.        ,   8.66666667,  16.33333333,  24.        ])

In [70]:
a
a[0:2]
a[:6:2] = -1000 

array([[2, 2],
       [3, 3],
       [4, 4]])

array([[2, 2],
       [3, 3]])

In [71]:
a

array([[-1000, -1000],
       [    3,     3],
       [-1000, -1000]])

In [11]:
np.array([1,0,0,1]).dtype
# - np.array([0,1,0,1])


dtype('int64')